/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package traccia;

import traccia.Transaction;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    String action = "";
  }
}
